CREATE TABLE todos (
  id UUID PRIMARY KEY,
  text TEXT NOT NULL,
  completed BOOLEAN NOT NULL,
  creator TEXT NOT NULL,
  doneBy TEXT,
  dateCreated TIMESTAMP WITH TIME ZONE NOT NULL,
  dateCompleted TIMESTAMP WITH TIME ZONE
);
