CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

ALTER TABLE "todo" 
    ALTER COLUMN "id" SET DATA TYPE uuid 
    USING uuid_generate_v4();

ALTER TABLE "todo" 
    ALTER COLUMN "id" SET DEFAULT uuid_generate_v4();

ALTER TABLE "todo" 
    ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMP WITH TIME ZONE 
    USING "dateCreated"::TIMESTAMP WITH TIME ZONE;

ALTER TABLE "todo" 
    ALTER COLUMN "dateCompleted" SET DATA TYPE TIMESTAMP WITH TIME ZONE 
    USING "dateCompleted"::TIMESTAMP WITH TIME ZONE;

CREATE TABLE todos (
  id UUID PRIMARY KEY,
  text TEXT NOT NULL,
  completed BOOLEAN NOT NULL,
  creator TEXT NOT NULL,
  doneBy TEXT,
  dateCreated TIMESTAMP WITH TIME ZONE NOT NULL,
  dateCompleted TIMESTAMP WITH TIME ZONE
);
